# Generated by Django 5.1 on 2025-02-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_board_code_alter_note_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='date_end',
        ),
    ]
